
insert into country (name, isocode, iso3, numcode) values ('Afghanistan', 'AF', 'AFG', 4);
insert into country (name, isocode, iso3, numcode) values ('Åland Islands', 'AX', 'ALA', 248);
insert into country (name, isocode, iso3, numcode) values ('Albania', 'AL', 'ALB', 8);
insert into country (name, isocode, iso3, numcode) values ('Algeria', 'DZ', 'DZA', 12);
insert into country (name, isocode, iso3, numcode) values ('American Samoa', 'AS', 'ASM', 16);
insert into country (name, isocode, iso3, numcode) values ('Andorra', 'AD', 'AND', 20);
insert into country (name, isocode, iso3, numcode) values ('Angola', 'AO', 'AGO', 24);
insert into country (name, isocode, iso3, numcode) values ('Anguilla', 'AI', 'AIA', 660);
insert into country (name, isocode, iso3, numcode) values ('Antarctica', 'AQ', 'ATA', 10);
insert into country (name, isocode, iso3, numcode) values ('Antigua and Barbuda', 'AG', 'ATG', 28);
insert into country (name, isocode, iso3, numcode) values ('Argentina', 'AR', 'ARG', 32);
insert into country (name, isocode, iso3, numcode) values ('Armenia', 'AM', 'ARM', 51);
insert into country (name, isocode, iso3, numcode) values ('Aruba', 'AW', 'ABW', 533);
insert into country (name, isocode, iso3, numcode) values ('Australia', 'AU', 'AUS', 36);
insert into country (name, isocode, iso3, numcode) values ('Austria', 'AT', 'AUT', 40);
insert into country (name, isocode, iso3, numcode) values ('Azerbaijan', 'AZ', 'AZE', 31);
insert into country (name, isocode, iso3, numcode) values ('Bahamas', 'BS', 'BHS', 44);
insert into country (name, isocode, iso3, numcode) values ('Bahrain', 'BH', 'BHR', 48);
insert into country (name, isocode, iso3, numcode) values ('Bangladesh', 'BD', 'BGD', 50);
insert into country (name, isocode, iso3, numcode) values ('Barbados', 'BB', 'BRB', 52);
insert into country (name, isocode, iso3, numcode) values ('Belarus', 'BY', 'BLR', 112);
insert into country (name, isocode, iso3, numcode) values ('Belgium', 'BE', 'BEL', 56);
insert into country (name, isocode, iso3, numcode) values ('Belize', 'BZ', 'BLZ', 84);
insert into country (name, isocode, iso3, numcode) values ('Benin', 'BJ', 'BEN', 204);
insert into country (name, isocode, iso3, numcode) values ('Bermuda', 'BM', 'BMU', 60);
insert into country (name, isocode, iso3, numcode) values ('Bhutan', 'BT', 'BTN', 64);
insert into country (name, isocode, iso3, numcode) values ('Bolivia, Plurinational State of', 'BO', 'BOL', 68);
insert into country (name, isocode, iso3, numcode) values ('Bonaire, Sint Eustatius and Saba', 'BQ', 'BES', 535);
insert into country (name, isocode, iso3, numcode) values ('Bosnia and Herzegovina', 'BA', 'BIH', 70);
insert into country (name, isocode, iso3, numcode) values ('Botswana', 'BW', 'BWA', 72);
insert into country (name, isocode, iso3, numcode) values ('Bouvet Island', 'BV', 'BVT', 74);
insert into country (name, isocode, iso3, numcode) values ('Brazil', 'BR', 'BRA', 76);
insert into country (name, isocode, iso3, numcode) values ('British Indian Ocean Territory', 'IO', 'IOT', 86);
insert into country (name, isocode, iso3, numcode) values ('Brunei Darussalam', 'BN', 'BRN', 96);
insert into country (name, isocode, iso3, numcode) values ('Bulgaria', 'BG', 'BGR', 100);
insert into country (name, isocode, iso3, numcode) values ('Burkina Faso', 'BF', 'BFA', 854);
insert into country (name, isocode, iso3, numcode) values ('Burundi', 'BI', 'BDI', 108);
insert into country (name, isocode, iso3, numcode) values ('Cambodia', 'KH', 'KHM', 116);
insert into country (name, isocode, iso3, numcode) values ('Cameroon', 'CM', 'CMR', 120);
insert into country (name, isocode, iso3, numcode) values ('Canada', 'CA', 'CAN', 124);
insert into country (name, isocode, iso3, numcode) values ('Cabo Verde', 'CV', 'CPV', 132);
insert into country (name, isocode, iso3, numcode) values ('Cayman Islands', 'KY', 'CYM', 136);
insert into country (name, isocode, iso3, numcode) values ('Central African Republic', 'CF', 'CAF', 140);
insert into country (name, isocode, iso3, numcode) values ('Chad', 'TD', 'TCD', 148);
insert into country (name, isocode, iso3, numcode) values ('Chile', 'CL', 'CHL', 152);
insert into country (name, isocode, iso3, numcode) values ('China', 'CN', 'CHN', 156);
insert into country (name, isocode, iso3, numcode) values ('Christmas Island', 'CX', 'CXR', 162);
insert into country (name, isocode, iso3, numcode) values ('Cocos (Keeling) Islands', 'CC', 'CCK', 166);
insert into country (name, isocode, iso3, numcode) values ('Colombia', 'CO', 'COL', 170);
insert into country (name, isocode, iso3, numcode) values ('Comoros', 'KM', 'COM', 174);
insert into country (name, isocode, iso3, numcode) values ('Congo', 'CG', 'COG', 178);
insert into country (name, isocode, iso3, numcode) values ('Congo, the Democratic Republic of the', 'CD', 'COD', 180);
insert into country (name, isocode, iso3, numcode) values ('Cook Islands', 'CK', 'COK', 184);
insert into country (name, isocode, iso3, numcode) values ('Costa Rica', 'CR', 'CRI', 188);
insert into country (name, isocode, iso3, numcode) values ('Côte d''Ivoire', 'CI', 'CIV', 384);
insert into country (name, isocode, iso3, numcode) values ('Croatia', 'HR', 'HRV', 191);
insert into country (name, isocode, iso3, numcode) values ('Cuba', 'CU', 'CUB', 192);
insert into country (name, isocode, iso3, numcode) values ('Curaçao', 'CW', 'CUW', 531);
insert into country (name, isocode, iso3, numcode) values ('Cyprus', 'CY', 'CYP', 196);
insert into country (name, isocode, iso3, numcode) values ('Czech Republic', 'CZ', 'CZE', 203);
insert into country (name, isocode, iso3, numcode) values ('Denmark', 'DK', 'DNK', 208);
insert into country (name, isocode, iso3, numcode) values ('Djibouti', 'DJ', 'DJI', 262);
insert into country (name, isocode, iso3, numcode) values ('Dominica', 'DM', 'DMA', 212);
insert into country (name, isocode, iso3, numcode) values ('Dominican Republic', 'DO', 'DOM', 214);
insert into country (name, isocode, iso3, numcode) values ('Ecuador', 'EC', 'ECU', 218);
insert into country (name, isocode, iso3, numcode) values ('Egypt', 'EG', 'EGY', 818);
insert into country (name, isocode, iso3, numcode) values ('El Salvador', 'SV', 'SLV', 222);
insert into country (name, isocode, iso3, numcode) values ('Equatorial Guinea', 'GQ', 'GNQ', 226);
insert into country (name, isocode, iso3, numcode) values ('Eritrea', 'ER', 'ERI', 232);
insert into country (name, isocode, iso3, numcode) values ('Estonia', 'EE', 'EST', 233);
insert into country (name, isocode, iso3, numcode) values ('Ethiopia', 'ET', 'ETH', 231);
insert into country (name, isocode, iso3, numcode) values ('Falkland Islands (Malvinas)', 'FK', 'FLK', 238);
insert into country (name, isocode, iso3, numcode) values ('Faroe Islands', 'FO', 'FRO', 234);
insert into country (name, isocode, iso3, numcode) values ('Fiji', 'FJ', 'FJI', 242);
insert into country (name, isocode, iso3, numcode) values ('Finland', 'FI', 'FIN', 246);
insert into country (name, isocode, iso3, numcode) values ('France', 'FR', 'FRA', 250);
insert into country (name, isocode, iso3, numcode) values ('French Guiana', 'GF', 'GUF', 254);
insert into country (name, isocode, iso3, numcode) values ('French Polynesia', 'PF', 'PYF', 258);
insert into country (name, isocode, iso3, numcode) values ('French Southern Territories', 'TF', 'ATF', 260);
insert into country (name, isocode, iso3, numcode) values ('Gabon', 'GA', 'GAB', 266);
insert into country (name, isocode, iso3, numcode) values ('Gambia', 'GM', 'GMB', 270);
insert into country (name, isocode, iso3, numcode) values ('Georgia', 'GE', 'GEO', 268);
insert into country (name, isocode, iso3, numcode) values ('Germany', 'DE', 'DEU', 276);
insert into country (name, isocode, iso3, numcode) values ('Ghana', 'GH', 'GHA', 288);
insert into country (name, isocode, iso3, numcode) values ('Gibraltar', 'GI', 'GIB', 292);
insert into country (name, isocode, iso3, numcode) values ('Greece', 'GR', 'GRC', 300);
insert into country (name, isocode, iso3, numcode) values ('Greenland', 'GL', 'GRL', 304);
insert into country (name, isocode, iso3, numcode) values ('Grenada', 'GD', 'GRD', 308);
insert into country (name, isocode, iso3, numcode) values ('Guadeloupe', 'GP', 'GLP', 312);
insert into country (name, isocode, iso3, numcode) values ('Guam', 'GU', 'GUM', 316);
insert into country (name, isocode, iso3, numcode) values ('Guatemala', 'GT', 'GTM', 320);
insert into country (name, isocode, iso3, numcode) values ('Guernsey', 'GG', 'GGY', 831);
insert into country (name, isocode, iso3, numcode) values ('Guinea', 'GN', 'GIN', 324);
insert into country (name, isocode, iso3, numcode) values ('Guinea-Bissau', 'GW', 'GNB', 624);
insert into country (name, isocode, iso3, numcode) values ('Guyana', 'GY', 'GUY', 328);
insert into country (name, isocode, iso3, numcode) values ('Haiti', 'HT', 'HTI', 332);
insert into country (name, isocode, iso3, numcode) values ('Heard Island and McDonald Islands', 'HM', 'HMD', 334);
insert into country (name, isocode, iso3, numcode) values ('Holy See (Vatican City State)', 'VA', 'VAT', 336);
insert into country (name, isocode, iso3, numcode) values ('Honduras', 'HN', 'HND', 340);
insert into country (name, isocode, iso3, numcode) values ('Hong Kong', 'HK', 'HKG', 344);
insert into country (name, isocode, iso3, numcode) values ('Hungary', 'HU', 'HUN', 348);
insert into country (name, isocode, iso3, numcode) values ('Iceland', 'IS', 'ISL', 352);
insert into country (name, isocode, iso3, numcode) values ('India', 'IN', 'IND', 356);
insert into country (name, isocode, iso3, numcode) values ('Indonesia', 'ID', 'IDN', 360);
insert into country (name, isocode, iso3, numcode) values ('Iran, Islamic Republic of', 'IR', 'IRN', 364);
insert into country (name, isocode, iso3, numcode) values ('Iraq', 'IQ', 'IRQ', 368);
insert into country (name, isocode, iso3, numcode) values ('Ireland', 'IE', 'IRL', 372);
insert into country (name, isocode, iso3, numcode) values ('Isle of Man', 'IM', 'IMN', 833);
insert into country (name, isocode, iso3, numcode) values ('Israel', 'IL', 'ISR', 376);
insert into country (name, isocode, iso3, numcode) values ('Italy', 'IT', 'ITA', 380);
insert into country (name, isocode, iso3, numcode) values ('Jamaica', 'JM', 'JAM', 388);
insert into country (name, isocode, iso3, numcode) values ('Japan', 'JP', 'JPN', 392);
insert into country (name, isocode, iso3, numcode) values ('Jersey', 'JE', 'JEY', 832);
insert into country (name, isocode, iso3, numcode) values ('Jordan', 'JO', 'JOR', 400);
insert into country (name, isocode, iso3, numcode) values ('Kazakhstan', 'KZ', 'KAZ', 398);
insert into country (name, isocode, iso3, numcode) values ('Kenya', 'KE', 'KEN', 404);
insert into country (name, isocode, iso3, numcode) values ('Kiribati', 'KI', 'KIR', 296);
insert into country (name, isocode, iso3, numcode) values ('Korea, Democratic People''s Republic of', 'KP', 'PRK', 408);
insert into country (name, isocode, iso3, numcode) values ('Korea, Republic of', 'KR', 'KOR', 410);
insert into country (name, isocode, iso3, numcode) values ('Kuwait', 'KW', 'KWT', 414);
insert into country (name, isocode, iso3, numcode) values ('Kyrgyzstan', 'KG', 'KGZ', 417);
insert into country (name, isocode, iso3, numcode) values ('Lao People''s Democratic Republic', 'LA', 'LAO', 418);
insert into country (name, isocode, iso3, numcode) values ('Latvia', 'LV', 'LVA', 428);
insert into country (name, isocode, iso3, numcode) values ('Lebanon', 'LB', 'LBN', 422);
insert into country (name, isocode, iso3, numcode) values ('Lesotho', 'LS', 'LSO', 426);
insert into country (name, isocode, iso3, numcode) values ('Liberia', 'LR', 'LBR', 430);
insert into country (name, isocode, iso3, numcode) values ('Libya', 'LY', 'LBY', 434);
insert into country (name, isocode, iso3, numcode) values ('Liechtenstein', 'LI', 'LIE', 438);
insert into country (name, isocode, iso3, numcode) values ('Lithuania', 'LT', 'LTU', 440);
insert into country (name, isocode, iso3, numcode) values ('Luxembourg', 'LU', 'LUX', 442);
insert into country (name, isocode, iso3, numcode) values ('Macao', 'MO', 'MAC', 446);
insert into country (name, isocode, iso3, numcode) values ('Macedonia, the former Yugoslav Republic of', 'MK', 'MKD', 807);
insert into country (name, isocode, iso3, numcode) values ('Madagascar', 'MG', 'MDG', 450);
insert into country (name, isocode, iso3, numcode) values ('Malawi', 'MW', 'MWI', 454);
insert into country (name, isocode, iso3, numcode) values ('Malaysia', 'MY', 'MYS', 458);
insert into country (name, isocode, iso3, numcode) values ('Maldives', 'MV', 'MDV', 462);
insert into country (name, isocode, iso3, numcode) values ('Mali', 'ML', 'MLI', 466);
insert into country (name, isocode, iso3, numcode) values ('Malta', 'MT', 'MLT', 470);
insert into country (name, isocode, iso3, numcode) values ('Marshall Islands', 'MH', 'MHL', 584);
insert into country (name, isocode, iso3, numcode) values ('Martinique', 'MQ', 'MTQ', 474);
insert into country (name, isocode, iso3, numcode) values ('Mauritania', 'MR', 'MRT', 478);
insert into country (name, isocode, iso3, numcode) values ('Mauritius', 'MU', 'MUS', 480);
insert into country (name, isocode, iso3, numcode) values ('Mayotte', 'YT', 'MYT', 175);
insert into country (name, isocode, iso3, numcode) values ('Mexico', 'MX', 'MEX', 484);
insert into country (name, isocode, iso3, numcode) values ('Micronesia, Federated States of', 'FM', 'FSM', 583);
insert into country (name, isocode, iso3, numcode) values ('Moldova, Republic of', 'MD', 'MDA', 498);
insert into country (name, isocode, iso3, numcode) values ('Monaco', 'MC', 'MCO', 492);
insert into country (name, isocode, iso3, numcode) values ('Mongolia', 'MN', 'MNG', 496);
insert into country (name, isocode, iso3, numcode) values ('Montenegro', 'ME', 'MNE', 499);
insert into country (name, isocode, iso3, numcode) values ('Montserrat', 'MS', 'MSR', 500);
insert into country (name, isocode, iso3, numcode) values ('Morocco', 'MA', 'MAR', 504);
insert into country (name, isocode, iso3, numcode) values ('Mozambique', 'MZ', 'MOZ', 508);
insert into country (name, isocode, iso3, numcode) values ('Myanmar', 'MM', 'MMR', 104);
insert into country (name, isocode, iso3, numcode) values ('Namibia', 'NA', 'NAM', 516);
insert into country (name, isocode, iso3, numcode) values ('Nauru', 'NR', 'NRU', 520);
insert into country (name, isocode, iso3, numcode) values ('Nepal', 'NP', 'NPL', 524);
insert into country (name, isocode, iso3, numcode) values ('Netherlands', 'NL', 'NLD', 528);
insert into country (name, isocode, iso3, numcode) values ('New Caledonia', 'NC', 'NCL', 540);
insert into country (name, isocode, iso3, numcode) values ('New Zealand', 'NZ', 'NZL', 554);
insert into country (name, isocode, iso3, numcode) values ('Nicaragua', 'NI', 'NIC', 558);
insert into country (name, isocode, iso3, numcode) values ('Niger', 'NE', 'NER', 562);
insert into country (name, isocode, iso3, numcode) values ('Nigeria', 'NG', 'NGA', 566);
insert into country (name, isocode, iso3, numcode) values ('Niue', 'NU', 'NIU', 570);
insert into country (name, isocode, iso3, numcode) values ('Norfolk Island', 'NF', 'NFK', 574);
insert into country (name, isocode, iso3, numcode) values ('Northern Mariana Islands', 'MP', 'MNP', 580);
insert into country (name, isocode, iso3, numcode) values ('Norway', 'NO', 'NOR', 578);
insert into country (name, isocode, iso3, numcode) values ('Oman', 'OM', 'OMN', 512);
insert into country (name, isocode, iso3, numcode) values ('Pakistan', 'PK', 'PAK', 586);
insert into country (name, isocode, iso3, numcode) values ('Palau', 'PW', 'PLW', 585);
insert into country (name, isocode, iso3, numcode) values ('Palestine, State of', 'PS', 'PSE', 275);
insert into country (name, isocode, iso3, numcode) values ('Panama', 'PA', 'PAN', 591);
insert into country (name, isocode, iso3, numcode) values ('Papua New Guinea', 'PG', 'PNG', 598);
insert into country (name, isocode, iso3, numcode) values ('Paraguay', 'PY', 'PRY', 600);
insert into country (name, isocode, iso3, numcode) values ('Peru', 'PE', 'PER', 604);
insert into country (name, isocode, iso3, numcode) values ('Philippines', 'PH', 'PHL', 608);
insert into country (name, isocode, iso3, numcode) values ('Pitcairn', 'PN', 'PCN', 612);
insert into country (name, isocode, iso3, numcode) values ('Poland', 'PL', 'POL', 616);
insert into country (name, isocode, iso3, numcode) values ('Portugal', 'PT', 'PRT', 620);
insert into country (name, isocode, iso3, numcode) values ('Puerto Rico', 'PR', 'PRI', 630);
insert into country (name, isocode, iso3, numcode) values ('Qatar', 'QA', 'QAT', 634);
insert into country (name, isocode, iso3, numcode) values ('Réunion', 'RE', 'REU', 638);
insert into country (name, isocode, iso3, numcode) values ('Romania', 'RO', 'ROU', 642);
insert into country (name, isocode, iso3, numcode) values ('Russian Federation', 'RU', 'RUS', 643);
insert into country (name, isocode, iso3, numcode) values ('Rwanda', 'RW', 'RWA', 646);
insert into country (name, isocode, iso3, numcode) values ('Saint Barthélemy', 'BL', 'BLM', 652);
insert into country (name, isocode, iso3, numcode) values ('Saint Helena, Ascension and Tristan da Cunha', 'SH', 'SHN', 654);
insert into country (name, isocode, iso3, numcode) values ('Saint Kitts and Nevis', 'KN', 'KNA', 659);
insert into country (name, isocode, iso3, numcode) values ('Saint Lucia', 'LC', 'LCA', 662);
insert into country (name, isocode, iso3, numcode) values ('Saint Martin (French part)', 'MF', 'MAF', 663);
insert into country (name, isocode, iso3, numcode) values ('Saint Pierre and Miquelon', 'PM', 'SPM', 666);
insert into country (name, isocode, iso3, numcode) values ('Saint Vincent and the Grenadines', 'VC', 'VCT', 670);
insert into country (name, isocode, iso3, numcode) values ('Samoa', 'WS', 'WSM', 882);
insert into country (name, isocode, iso3, numcode) values ('San Marino', 'SM', 'SMR', 674);
insert into country (name, isocode, iso3, numcode) values ('Sao Tome and Principe', 'ST', 'STP', 678);
insert into country (name, isocode, iso3, numcode) values ('Saudi Arabia', 'SA', 'SAU', 682);
insert into country (name, isocode, iso3, numcode) values ('Senegal', 'SN', 'SEN', 686);
insert into country (name, isocode, iso3, numcode) values ('Serbia', 'RS', 'SRB', 688);
insert into country (name, isocode, iso3, numcode) values ('Seychelles', 'SC', 'SYC', 690);
insert into country (name, isocode, iso3, numcode) values ('Sierra Leone', 'SL', 'SLE', 694);
insert into country (name, isocode, iso3, numcode) values ('Singapore', 'SG', 'SGP', 702);
insert into country (name, isocode, iso3, numcode) values ('Sint Maarten (Dutch part)', 'SX', 'SXM', 534);
insert into country (name, isocode, iso3, numcode) values ('Slovakia', 'SK', 'SVK', 703);
insert into country (name, isocode, iso3, numcode) values ('Slovenia', 'SI', 'SVN', 705);
insert into country (name, isocode, iso3, numcode) values ('Solomon Islands', 'SB', 'SLB', 90);
insert into country (name, isocode, iso3, numcode) values ('Somalia', 'SO', 'SOM', 706);
insert into country (name, isocode, iso3, numcode) values ('South Africa', 'ZA', 'ZAF', 710);
insert into country (name, isocode, iso3, numcode) values ('South Georgia and the South Sandwich Islands', 'GS', 'SGS', 239);
insert into country (name, isocode, iso3, numcode) values ('South Sudan', 'SS', 'SSD', 728);
insert into country (name, isocode, iso3, numcode) values ('Spain', 'ES', 'ESP', 724);
insert into country (name, isocode, iso3, numcode) values ('Sri Lanka', 'LK', 'LKA', 144);
insert into country (name, isocode, iso3, numcode) values ('Sudan', 'SD', 'SDN', 729);
insert into country (name, isocode, iso3, numcode) values ('Suriname', 'SR', 'SUR', 740);
insert into country (name, isocode, iso3, numcode) values ('Svalbard and Jan Mayen', 'SJ', 'SJM', 744);
insert into country (name, isocode, iso3, numcode) values ('Swaziland', 'SZ', 'SWZ', 748);
insert into country (name, isocode, iso3, numcode) values ('Sweden', 'SE', 'SWE', 752);
insert into country (name, isocode, iso3, numcode) values ('Switzerland', 'CH', 'CHE', 756);
insert into country (name, isocode, iso3, numcode) values ('Syrian Arab Republic', 'SY', 'SYR', 760);
insert into country (name, isocode, iso3, numcode) values ('Taiwan, Province of China', 'TW', 'TWN', 158);
insert into country (name, isocode, iso3, numcode) values ('Tajikistan', 'TJ', 'TJK', 762);
insert into country (name, isocode, iso3, numcode) values ('Tanzania, United Republic of', 'TZ', 'TZA', 834);
insert into country (name, isocode, iso3, numcode) values ('Thailand', 'TH', 'THA', 764);
insert into country (name, isocode, iso3, numcode) values ('Timor-Leste', 'TL', 'TLS', 626);
insert into country (name, isocode, iso3, numcode) values ('Togo', 'TG', 'TGO', 768);
insert into country (name, isocode, iso3, numcode) values ('Tokelau', 'TK', 'TKL', 772);
insert into country (name, isocode, iso3, numcode) values ('Tonga', 'TO', 'TON', 776);
insert into country (name, isocode, iso3, numcode) values ('Trinidad and Tobago', 'TT', 'TTO', 780);
insert into country (name, isocode, iso3, numcode) values ('Tunisia', 'TN', 'TUN', 788);
insert into country (name, isocode, iso3, numcode) values ('Turkey', 'TR', 'TUR', 792);
insert into country (name, isocode, iso3, numcode) values ('Turkmenistan', 'TM', 'TKM', 795);
insert into country (name, isocode, iso3, numcode) values ('Turks and Caicos Islands', 'TC', 'TCA', 796);
insert into country (name, isocode, iso3, numcode) values ('Tuvalu', 'TV', 'TUV', 798);
insert into country (name, isocode, iso3, numcode) values ('Uganda', 'UG', 'UGA', 800);
insert into country (name, isocode, iso3, numcode) values ('Ukraine', 'UA', 'UKR', 804);
insert into country (name, isocode, iso3, numcode) values ('United Arab Emirates', 'AE', 'ARE', 784);
insert into country (name, isocode, iso3, numcode) values ('United Kingdom', 'GB', 'GBR', 826);
insert into country (name, isocode, iso3, numcode) values ('United States', 'US', 'USA', 840);
insert into country (name, isocode, iso3, numcode) values ('United States Minor Outlying Islands', 'UM', 'UMI', 581);
insert into country (name, isocode, iso3, numcode) values ('Uruguay', 'UY', 'URY', 858);
insert into country (name, isocode, iso3, numcode) values ('Uzbekistan', 'UZ', 'UZB', 860);
insert into country (name, isocode, iso3, numcode) values ('Vanuatu', 'VU', 'VUT', 548);
insert into country (name, isocode, iso3, numcode) values ('Venezuela, Bolivarian Republic of', 'VE', 'VEN', 862);
insert into country (name, isocode, iso3, numcode) values ('Viet Nam', 'VN', 'VNM', 704);
insert into country (name, isocode, iso3, numcode) values ('Virgin Islands, British', 'VG', 'VGB', 92);
insert into country (name, isocode, iso3, numcode) values ('Virgin Islands, U.S.', 'VI', 'VIR', 850);
insert into country (name, isocode, iso3, numcode) values ('Wallis and Futuna', 'WF', 'WLF', 876);
insert into country (name, isocode, iso3, numcode) values ('Western Sahara', 'EH', 'ESH', 732);
insert into country (name, isocode, iso3, numcode) values ('Yemen', 'YE', 'YEM', 887);
insert into country (name, isocode, iso3, numcode) values ('Zambia', 'ZM', 'ZMB', 894);
insert into country (name, isocode, iso3, numcode) values ('Zimbabwe', 'ZW', 'ZWE', 716);
